language: scala
jdk: openjdk8
scala:
  - 2.12.8

branches:
  only:
    - master
    - /^v[0-9]/

cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.sbt        -name "*.lock"               -delete

notifications:
  email:
    on_success: never

services:
  - mysql
addons:
  apt:
    sources:
      - mysql-8.0-trusty
    packages:
      - mysql-server

env:
  global:
    - TRAVIS=true
    - CODECOV_TOKEN=e9c42dde-1f5b-4aa4-a641-84136f6f4e23

before_script:
  - sudo mysql -e 'CREATE DATABASE `timetable`;'
  - sudo mysql -e 'SHOW DATABASES;'
  - sudo mysql -e 'USE mysql;update user set authentication_string=PASSWORD("root") where user="root";update user set plugin="mysql_native_password";FLUSH PRIVILEGES;'
  - sudo mysql -u root --password="root" < src/main/resources/db/timetable-06.sql

script:
  - sbt generateJOOQ
  - sbt clean coverage test coverageReport

after_success:
  - sbt coveralls
  - bash <(curl -s https://codecov.io/bash)