language: scala
jdk: openjdk8
scala:
  - 2.12.8

branches:
  only:
    - master
    - /^v[0-9]/

cache:
  directories:
    - $HOME/.coursier
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.sbt        -name "*.lock"               -delete

notifications:
  email:
    on_success: never

services:
  - mysql


env:
  global:
    - TRAVIS=true

before_script:
  - sudo mysql -e 'CREATE DATABASE `timetable`;'
  - sudo mysql -e 'SHOW DATABASES;'
  - sudo mysql -e 'USE `timetable`;'

script:
  - sbt generateJOOQ
  - sbt clean coverage test coverageReport

after_success:
  - sbt coveralls